### ISSUE TITLE
oom on quarkus-maven-build due to jandex indexing

### ISSUE THREAD

**Issue by jcunliffe1** [smallrye/jandex#239]
https://github.com/quarkiverse/quarkus-logging-manager/issues/151
https://github.com/quarkusio/quarkus/issues/26875

Thread 'build-36' with ID = 88
	java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	java.util.Arrays.copyOf(Arrays.java:3536)
	org.jboss.jandex.Indexer.sizeToFit(Indexer.java:238)
	org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1881)
	org.jboss.jandex.Indexer.index(Indexer.java:1981)
	io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:49)
	io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:34)
	java.nio.file.Files.walkFileTree(Files.java:2804)
	java.nio.file.Files.walkFileTree(Files.java:2876)
	io.quarkus.deployment.steps.ApplicationIndexBuildStep.build(ApplicationIndexBuildStep.java:34)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:567)
	io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
	io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	io.quarkus.builder.BuildContext$$Lambda$823+0x000000080188d360.run(Native method)
	org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	java.lang.Thread.run(Thread.java:831)
	org.jboss.threads.JBossThread.run(JBossThread.java:501)

I got the heat dump with me. I'm generating around 50 files out open openapi spec, which themselves generate up to a few thousand lines using java immutable library

**Comment by jcunliffe1** [comment]
![image](https://user-images.githubusercontent.com/97282647/180485076-698fbe22-7751-44cd-90ca-3462a5aab19e.png)

this is on the application, which will load two libraries, each fairly normal sized.

**Comment by jcunliffe1** [comment]
on successful local builds, the jandex.idx built has 800 kb - not sure if that matters or is considered big.

**Comment by jcunliffe1** [comment]
after removing the jandex scans from annotation heavy maven modules, I could get rid of the OOM. would have preferred not to learn this lesson, but anyway - I'm good... until the next OOM happens out of nowhere.

**Comment by jcunliffe1** [comment]
I have confused a follow-up error with a preceding error - the oom is back.

**Comment by Ladicek** [comment]
It seems you're opening issues on random projects based on which thread was unlucky enough to hit the OOM condition, even though that has no relevance to the actual _cause_ of the OOM. I'm closing this issue until you can conclusively prove that it's Jandex who allocates excessive amount of memory. At the same time, I'll reopen the Quarkus issue and I ask you to continue _there_ instead of opening issues in other random projects. Thanks for understanding.

**Comment by jcunliffe1** [comment]
yes - it was fairly deterministic on the first 3 runs, but later I found the OOM to also happen elsewhere... it's a nice challenge to find out what's causing this, but it takes some time.

**Comment by Ladicek** [comment]
Please continue in the Quarkus issue: https://github.com/quarkusio/quarkus/issues/26875
