### ISSUE TITLE
jandex does not build with Maven 3.9.0

### ISSUE THREAD

**Issue by bdemers** [smallrye/jandex#298]
`impsort-maven-plugin` isn't compatible with the latest version of Maven
https://github.com/revelc/impsort-maven-plugin/issues/64

```
Execution sort-imports of goal net.revelc.code:impsort-maven-plugin:1.6.2:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.6.2:sort: org/codehaus/plexus/util/DirectoryScanner
```

`impsort-maven-plugin` has already released a fix and this version is already updated in `smallrye-build-parent` version 39.

Updating to the parent 39
* Builds successfully (locally) with Maven 3.8.7
* Reformats a handful of classes (whitespace)
* Fails with Maven 3.9.0, caused to an issue with the invoker tests (I stopped digging into the issue at this point)

**Comment by Ladicek** [comment]
Unfortunately the latest version of the impsort plugin requires Java 11, and I find it important for Jandex CI builds to run with Java 8. So this requires to jump through some hoops.

**Comment by bdemers** [comment]
I can relate, I've been working on a few projects that support older JVM's and it's increasingly becoming more difficult.
