### ISSUE TITLE
 classloader.getResource(entryName) return null

### ISSUE THREAD

**Issue by wangshihui** [smallrye/jandex#314]
In the `jar-index` feature
 classloader method:` classloader.getResource(entryName)` when the entryName is a drectory ,this method would return null. In some opensource tools use this feature to load the resouces in the same folder would fail.

**Comment by Ladicek** [comment]
I'm sorry, the issue description is not really actionable. Please provide some details, ideally a reproducer.

Specifically, note that Jandex does not implement any class loader, so any `ClassLoader.getResource(String)` calls you might be doing don't end up in Jandex.
